# Generated by Django 2.1.4 on 2018-12-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created', '-updated'], 'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
    ]
