# Generated by Django 2.1.4 on 2018-12-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
