# Generated by Django 2.1.4 on 2018-12-06 13:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_review_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_with_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна зі знижкою'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_video',
            field=models.URLField(blank=True, null=True, verbose_name='Відео огляд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
    ]
