# Generated by Django 2.1.4 on 2018-12-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20181210_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcharacteristic',
            options={'ordering': ['name'], 'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики продукту'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
    ]
