# Generated by Django 2.1.4 on 2018-12-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20181211_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
