# Generated by Django 2.1.4 on 2018-12-12 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20181212_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristic',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='catalog.Product'),
        ),
    ]
