# Generated by Django 2.1.4 on 2018-12-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20181212_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код товару'),
        ),
    ]
