# Generated by Django 2.1.4 on 2018-12-10 12:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.DecimalField(decimal_places=0, error_messages={'min_value': 'Номер телефону вказується без вісімки, повинен містити 10 цифр і не повинен починатися з нуля', 'unique': 'Пользователь с таким номера телефона уже существует'}, max_digits=10, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='номер телефону')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('delivery_type', models.CharField(choices=[('NP', 'Нова пошта'), ('CR', "Доставка кур'єром по Києву"), ('DW', 'Самовивіз з магазину партнерів')], default='DW', max_length=2)),
                ('customer_first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('customer_last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Прізвище')),
                ('customer_patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='По-батькові')),
                ('status', models.CharField(choices=[('processed', 'в обробці'), ('accepted', 'прийнято'), ('shipped', 'відправлено'), ('waiting', 'очікує в магазині'), ('canceled', 'скасовано'), ('paid', 'оплачено')], default='processed', max_length=32, verbose_name='Статус замовлення')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створений')),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='catalog.Product')),
            ],
        ),
    ]
