# Generated by Django 2.1.4 on 2018-12-07 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181207_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='По-батькові'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.DecimalField(decimal_places=0, default=1, error_messages={'min_value': 'Номер телефону вказується без вісімки, повинен містити 10 цифр і не повинен починатися з нуля', 'unique': 'Пользователь с таким номера телефона уже существует'}, max_digits=10, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='номер телефону'),
            preserve_default=False,
        ),
    ]
